export const PLAYER_SPEED = 7;
export const PLAYER_HEIGHT = 0.9;
export const PLAYER_HEALTH = 100;
export const BULLET_SPEED = 35;
export const BULLET_LIFETIME = 2800;
export const BULLET_DAMAGE = 50;       // player → bot: 2-shot kill
export const BOT_BULLET_DAMAGE = 15;   // bot → player: ~7 shots to die
export const BULLET_RADIUS = 0.9;
export const BOT_SPEED = 3.0;
export const BOT_HEALTH = 100;
export const BOT_SHOOT_RANGE = 11;
export const BOT_CHASE_RANGE = 20;
export const BOT_SHOOT_COOLDOWN = 1.8; // bots fire slower
export const BOT_SPREAD = 0.14;        // bots are less accurate
export const RESPAWN_TIME = 3;
export const MATCH_DURATION = 120;
export const MAP_HALF = 24;
export const MOUSE_SENSITIVITY = 0.0022;
export const RELOAD_TIME = 2;
export const MAX_AMMO = 30;
export const BOT_NAMES = ['CIPHER', 'VIPER', 'GHOST', 'NEXUS', 'BLAZE', 'ROGUE'];
export const BOT_COLORS = ['#ff3333', '#3399ff', '#ff9900', '#cc33ff', '#00ccff', '#ff6699'];
